### ISSUE TITLE
Git URL in README's initial npm install command receives no response

### ISSUE THREAD

**Issue by ncolesummers** [ellucian-developer/experience-extension-server-util#5]
Steps to reproduce:

```sh
npm install git+https://git.ellucian.com/scm/rang/experience-extension-server-util.git            
npm ERR! code 128
npm ERR! A git connection error occurred
npm ERR! command git --no-replace-objects ls-remote https://git.ellucian.com/scm/rang/experience-extension-server-util.git
npm ERR! fatal: unable to access 'https://git.ellucian.com/scm/rang/experience-extension-server-util.git/': Failed to connect to git.ellucian.com port 443 after 150080 ms: Operation timed out
```
[2022-08-09T22_26_49_892Z-debug-0.log](https://github.com/ellucian-developer/experience-extension-server-util/files/9295001/2022-08-09T22_26_49_892Z-debug-0.log)

**Comment by ellucianBret** [comment]
Sorry, bad URL in the document. I will fix it. For now use this:

npm install git+https://github.com/ellucian-developer/experience-extension-server-util.git

Bret

**Comment by ellucianBret** [comment]
I pushed a fix to master.

**Comment by ncolesummers** [comment]
Thank you for the quick fix, it's greatly appreciated!
